//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BandAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Musician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musician()
        {
            this.Band = new HashSet<Band>();
        }

        public int idMusician { get; set; }

        [Required]
        [Display(Name = "Nome")]
        [StringLength(50)]
        public string name { get; set; }

        [Display(Name = "Instrumento")]
        public int fk_instrument { get; set; }

        public virtual Instrument Instrument { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Band> Band { get; set; }
    }
}
